version: 0.2
phases:
  pre_build:
    commands:
      - dotnet restore ./AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  build:
    commands:
      - dotnet build ./AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ AWSCodePipelineDemo/AWSCodePipelineDemo.csproj
artifacts:
  files:
    - '**/*'
